export const LocalTextsEn = {
  t_app_menu: 'Menu',
  t_app_menu_section_profile: 'Profile',
  t_app_menu_section_preferences: 'Preferences',
  t_app_menu_section_more: 'More',
  t_app_menu_nameandemail: 'Name & Email',
  t_app_teryname: 'Terry Jenkins',
  t_app_teryemail: 'terryjenkins@gmail.com',
  t_app_passwpord: 'Password',
  t_app_time_region: 'Time & Region',
  t_app_notify: 'Notifications',
  t_app_time_privacy: 'Privacy & Security',
  t_app_aperance: 'Appearance',
  t_app_contact: 'Contact Support',
  t_app_therms: 'Terms of Service',
  t_app_policy: 'Privacy Policy',
  t_app_app_version: 'App Version - 1.43.7',
  t_app_app_logout: 'Log Out',
};
